blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<post_id>\d+)/$', views.post, name='post'),
)

jblog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls',namespace='blog')),
    url(r'^pages/',include('django.contrib.flatpages.urls')),
)

blog/models.py
import datetime

from django.db import models
from django.utils import timezone

class Post(models.Model):
	title = models.CharField('Title',max_length=200)
	pub_date = models.DateTimeField('Date Published')
	entry = models.TextField(max_length=10000)

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=7)
	was_published_recently.short_description = 'Published recently (within last week)?'

	def __unicode__(self):
		return self.title

blog/views.py
import json

from datetime import datetime

from django.shortcuts import render, get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string

from blog.models import Post

def index(request):
	posts = Post.objects.all().order_by('-pub_date')[:5]
	return render(request,'blog/index.html',{'posts':posts,})

def post(request, post_id):
	post = get_object_or_404(Post,pk=post_id)
	return render(request,'blog/post.html',{'post':post,})

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}

{% if posts %}
    {% for post in posts %}
		<h1><a href="{% url 'blog:post' post.pk %}">{{ post.title }}</a></h1>
		<p class='lead'>{{ post.entry|safe }}</p>
	    <p class='postdate'>Posted: {{ post.pub_date }}</p>
		<hr>
    {% endfor %}
{% else %}
	<h1>There are currently no posts!</h1>
{% endif %}

{% endblock %}

blog/templates/blog/post.html
{% extends "base.html" %}

{% block content %}

<h1>{{ post.title }}</h1>
<p class='lead'>{{ post.entry|safe }}</p>
<p class='postdate'>Posted: {{ post.pub_date }}</p>
<a class="btn btn-default" href="/blog/">Back</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jolo's Blog{% block title %}{% endblock %}</title>

    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap-lumen.min.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.theme.min.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css">

    {% block script %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" data-target=".bs-navbar-collapse" data-toggle="collapse" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Jolo's Portfolio</a>
            </div>

            <div class="collapse navbar-collapse bs-navbar-collapse">
                <ul class='nav navbar-nav'>
                    <li><a href="/blog/">Blog</a></li>
                    <li><a href="/samples/">Samples</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="http://blproduction.herokuapp.com/blist/" target="_blank"><span class="glyphicon glyphicon-list-alt"></span> Bucket List</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class='nav navbar-nav navbar-right'>
                    <li><a href="/about/">About</a></li>
                    <li><a href="/credits/">Credits</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class='container'>
        <div class='row'>
            <div class='col-xs-12'>
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

<h1>{{ newest.title }}</h1>
<p class='postdate'>Posted: {{ newest.pub_date }}</p>
<p class="lead">
	{{ newest.entry|safe|truncatewords:200 }} <a href="{% url 'blog:post' newest.pk %}">read more</a>.
</p>

<hr>

<h1>Welcome</h1>
<p class="lead">
	{{ flatpage.content|safe }}
</p>

{% endblock %}